language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - python -m pytest tests_prometheus_udp_gateway.py --cov=prometheus_udp_gateway.py --cov-report=term

after_success:
    - codecov
